### ISSUE TITLE
Contribute to Express

### ISSUE THREAD

**Issue by wesleytodd** [seanpmaxwell/express-generator-typescript#1]
Hi Sean,

I am a member of the Express TC.  I have been recently been [working on a replacement to the (out of date IMO) express generator](https://github.com/wesleytodd/create-express-app).  One of the things I wanted before I finalized the documentation on it and moved it over as the official generator was a TS version.

I just happened to see [a tweet which had a link to this repo](https://twitter.com/JavaScriptDaily/status/1140016883548250112), and it makes much more sense to me to have someone with more expertise in TS than I to write the template.  I was wondering if you would be willing to collaborate on an "official" project scaffold?

On a side note, if you are up for helping, we have need of people willing to help us support the typing declarations: https://github.com/expressjs/express/issues/2818

**Comment by seanpmaxwell** [comment]
Wow, this feels like an honor! Would the TS version be done by providing an option to the current express-generator app like `npx express-generator --ts` or would it be a fully standalone npm package? If my package _express-generator-typescript_ could somehow become the official version I would be more than willing to help out and make modifications depending on peoples' needs/feedback. If not, I'm still interested but I'd need to see how much time I have to start a fully new project. I still have a full-time job and am working on a pseudo-startup with someone.

**Comment by wesleytodd** [comment]
Ha, well honor or not, I am really just a beggar asking for TS help :)

For the work involved, it would be an addition to the module I linked above as the replacement I am working on.  It would most likely be a new template like you can see in the `templates` directory.  It would also be setting up the modules a TS project requires as the options to `create-package-json`.  In all it should be a pretty small amount of work. The new generator is attempting to make it more easy to add features.  The existing `express-generator` is a bit restrictive in the way it was written.

I am sure we would also need some review by other TS users, and the hope is we can get some other contributors as well.  As for time commitment, I fully understand, I and the other Express team members also do it on top of our normal work.  If it is too much that is understandable, but it is better to ask than not.

**Comment by seanpmaxwell** [comment]
If all you want is new template I guess count me in. I think I could probably spend a day to just copy and paste my current template into your module but maybe stripped down a little OR (maybe this is a dumb idea) create-express-app could use express-Typescript-generator to create new projects

**Comment by seanpmaxwell** [comment]
Would you still like me to pull request and paste in a template for TypeScript?

**Comment by wesleytodd** [comment]
For sure! That repo is still in progress, but I discussed it at the last TC meeting and it seems like it is a good direction to replace the existing generator.
