### ISSUE TITLE
How do I add the --inspect flag to the command line arguments so that I can use nodejs debugger, I am finding it difficult to add the --inspect tag

### ISSUE THREAD

**Issue by sheghun** [seanpmaxwell/express-generator-typescript#13]

**Comment by seanpmaxwell** [comment]
I use the VSCODE debugger but i'd assume it'd be something like node -r ts-node/register -r tsconfig-paths/register --inspect

**Comment by seanpmaxwell** [comment]
Did you get it working? Can I close this issue?

**Comment by terary** [comment]
I am having same issue but with vscode.  

nodemon.json:
    "exec": "ts-node -r tsconfig-paths/register --inspect  ./src --env=development"
gives error:
Error: Unknown or unexpected option: --inspect
    at arg (/mypart/tmc/tmp/express-tsx/whatwhat/node_modules/arg/index.js:88:19)
    at main (/mypart/tmc/tmp/express-tsx/whatwhat/node_modules/ts-node/dist/bin.js:34:18)
    at Object.<anonymous> (/mypart/tmc/tmp/express-tsx/whatwhat/node_modules/ts-node/dist/bin.js:404:5)



-----------------
On a side note- thank you so much for putting together this shell application.  Though I am having some minor issues it appears to be well done.

**Comment by terary** [comment]
nodemon.json
  "exec": "NODE_OPTIONS='--inspect' ts-node -r tsconfig-paths/register  ./src --env=development"
Seems to do the trick.
