### ISSUE TITLE
Debugging the application

### ISSUE THREAD

**Issue by valekar** [seanpmaxwell/express-generator-typescript#16]
Hello all, 
I am a newbie to node and typescript. I wanted to debug the user APIs. Is there any way to accomplish it? Any hint would be of great help for me.

**Comment by seanpmaxwell** [comment]
I use vscode. Here's a snippet of the configuration I use:         `{
            "type": "node",
            "request": "launch",
            "name": "Debug Dev Env",
            "runtimeArgs": [
                "-r", "ts-node/register",
                "-r", "tsconfig-paths/register",
            ],
            "args": [
                "${workspaceFolder:PhotonSuite}/src/index.ts"
            ],
            "protocol": "inspector"
        },`

**Comment by seanpmaxwell** [comment]
If you're on windows also make sure you have Windows-build-tools for Node installed and `node-gyp` installed too.

**Comment by valekar** [comment]
@seanpmaxwell : thanks for the info, I got it working by attaching the debugger of vscode to node processor. I created a new debug configuration in launch.json. 

Thanks again :)

**Comment by seanpmaxwell** [comment]
Welcome, closing this issue.
