### ISSUE TITLE
Error when using --with-auth option and, no bcrypt binary available and no build tools

### ISSUE THREAD

**Issue by MBRGA** [seanpmaxwell/express-generator-typescript#17]
I am running the express-generator-typescript tool on Windows, via `npx express-generator-typescript --with-auth "my-app-name"`. I am getting the following error:

`npm i -s express dotenv http-status-codes morgan cookie-parser winston module-alias command-line-args bcrypt randomstring jsonwebtoken`

By running the verbose version of the above `npm` command manually I eventually worked out that it was the bcrypt package that was causing the problem because I didn't have the build tools installed. Would it be possible to add some clearer error messages so that this failure case is easier to diagnose?

**Comment by seanpmaxwell** [comment]
Thanks I updated the readme with a notice to Windows users

**Comment by kabirvirji** [comment]
I also encountered this issue on Mac
