### ISSUE TITLE
daos

### ISSUE THREAD

**Issue by jpbamberg1993** [seanpmaxwell/express-generator-typescript#18]
Just wondering what daos stood for?

**Comment by seanpmaxwell** [comment]
Data-Access-Object. It's pattern to follow for those who like to use raw SQL. Keeps you APIs cleaner.

**Comment by imbrok** [comment]
"The DAO as its name implies is for accessing/updating the underlying storage regarding a certain entity/class."
[This link](https://stackoverflow.com/questions/19154202/data-access-object-dao-in-java) explains many more about DAO.
