### ISSUE TITLE
tslint is being deprecated

### ISSUE THREAD

**Issue by naknode** [seanpmaxwell/express-generator-typescript#19]
Hi there, TSLint is being deprecated in favor of ES Lint. Will we be seeing changes soon or can put in a PR?

**Comment by seanpmaxwell** [comment]
yeah I'm aware that the deprecation was completed not too long ago. Problem is I like to put two lines between my classes method and i like to use this library tslint-line-between-class-members whereas the eslint counterpart only lets you use one line. I was planning to upgrade once the there's an equivalent library feature.

**Comment by pingustar** [comment]
@seanpmaxwell 

would also really like to see ESLint and Prettier support!

Otherwise really great tool! I use it alot 👍
