### ISSUE TITLE
ESLint Error, any way around it?

### ISSUE THREAD

**Issue by mikeerickson** [seanpmaxwell/express-generator-typescript#2]
I am fairly new to TypeScript.  Using this starter (thanks btw) I receive an error when running eslint

```js
Users/mikee/Documents/code/typescript/express-ts/src/entities/User.ts
  3:3  error  Parsing error: Unexpected token

  1 | interface IUser {
  2 |   name: string
> 3 |   email: string
    |   ^
  4 | }
  5 | 
  6 | class User implements IUser {

✖ 1 problem (1 error, 0 warnings)
```

**Comment by seanpmaxwell** [comment]
Hey so linting in eslint is still in its infancy for TypeScript and there are some issues with it. Most people (especially for Node) are still using tslint. I haven't tried this with eslint. Once TypeScript support is solid in eslint I'll updated the package to use that instead.

**Comment by mikeerickson** [comment]
Sounds good to me. I did get it finally work however. I will post what I had to do tomorrow so this issues has a working solution for future devs who may have same issue.

**Comment by seanpmaxwell** [comment]
Thanks
