### ISSUE TITLE
npm start not working after generating build

### ISSUE THREAD

**Issue by yogeshvyas** [seanpmaxwell/express-generator-typescript#21]
I created the build from given command and ran also but nothing happend

**Comment by seanpmaxwell** [comment]
Hmm, I just tried it and it's working fine. Did you do:

`npm run build`
`npm start`

navigate to `localhost:8081` in the browser? Keep in mind production mode logs are printed to a file not the console

**Comment by yogeshvyas** [comment]
Thank you for the quick reply.  Please let me know how to deploy it on the ubuntu server or any.

**Comment by seanpmaxwell** [comment]
Just copy the `dist/` folder along with the `package.json` file (don't put package json in the dist folder) to wherever you want it to go. Do `npm install --only=prod` in the remote folder.

**Comment by cicineer** [comment]
cool, solved
