### ISSUE TITLE
Add support for nodemon debugging

### ISSUE THREAD

**Issue by DTX-92** [seanpmaxwell/express-generator-typescript#25]
Solid boilerplate, thank you
But i wasn't able to implement nodemon debugging (when debugger reconnects when you change code).
I've spent several hours to follow [this](https://dev.to/oieduardorabelo/nodejs-with-typescript-debug-inside-vscode-and-nodemon-23o7) article, but wasn't able to make module-aliasing work.

**Comment by seanpmaxwell** [comment]
Are you on Windows? There's a note at the bottom of the Readme about debugging on windows.

**Comment by DTX-92** [comment]
> Are you on Windows? There's a note at the bottom of the Readme about debugging on windows.

No, MacOs, 10.14

Btw, I've found your launch.json in https://github.com/seanpmaxwell/express-generator-typescript/issues/20
It works, but it drops debugger every time you make changes to the code

**Comment by seanpmaxwell** [comment]
oh yeah now I remember I don't use nodemon with the debugger. There's no need, in the debugger you can hit the restart button.

**Comment by Marcus-Rise** [comment]
`node --inspect -r ts-node/register -r tsconfig-paths/register ./src --env=development`
#32

**Comment by seanpmaxwell** [comment]
Sorry buddy I think this is a bit too trivial and steers a bit from a default setup. I don't want `--inspect` configured by default. People can modify their nodemonConfig if they want debugging enable. I tell you this though, I'll update the readme and tell them where to add `--inspect` if they want debugging enabled.
