### ISSUE TITLE
Why token generate at client side.

### ISSUE THREAD

**Issue by chhaunkar96** [seanpmaxwell/express-generator-typescript#26]
We can see in the following request that token is going from the client-side with login details. why the token is generated on the client-side?? Can anyone explain it ?? It's confusing.

![image](https://user-images.githubusercontent.com/29665934/81102263-02b5f180-8f2d-11ea-8cc3-c84bd7610169.png)

**Comment by seanpmaxwell** [comment]
The token isn't generated client side. The token is generated server-side in the login route but does get put in a cookie and cookies are stored client-side. So you'll be able to see the token in the browser. But that doesn't mean it's generated there.

**Comment by chhaunkar96** [comment]
It was my silly mistake. I reported issue at wrong place. It was not from this generator.
