### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by iampeters** [seanpmaxwell/express-generator-typescript#28]
hello, thanks for this package.
However, when I try to run it for production using your documentation <code>npm start</code>
i get these errors 

<code>
halloween@0.0.0 start /Users/peterschikezie/iCloud Drive (Archive)/Documents/projects/halloween
> node -r module-alias/register ./dist

internal/modules/cjs/loader.js:796
    throw err;
    ^
Error: Cannot find module '/Users/peterschikezie/iCloud Drive (Archive)/Documents/projects/halloween/dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._resolveFilename (/Users/peterschikezie/iCloud Drive (Archive)/Documents/projects/halloween/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
</code>

Is there something i am not doing correctly?
i have Googled and found no help. Please help me out.

Thanks in advance

**Comment by seanpmaxwell** [comment]
Did you do `npm run build` first?

**Comment by iampeters** [comment]
yes i did.

**Comment by seanpmaxwell** [comment]
you don't need to run `npm install` . I think you're using a different module mine is `npx express-generator-typescript` you just typed `express-typescript-generator`

**Comment by iampeters** [comment]
That's a typo. I am actually using the same package.

**Comment by seanpmaxwell** [comment]
Hmmm I just walked through the steps and everything worked fine for me. Seems like you're doing things under something called iCould drive. Try doing it in a different folder like your desktop.

**Comment by iampeters** [comment]
i went through the build again and i found out that these files `index.ts, LoadEnv.ts, Server.ts` along with most of my code were not transpiled and copied into dust folder.

**Comment by iampeters** [comment]
> Hmmm I just walked through the steps and everything worked fine for me. Seems like you're doing things under something called iCould drive. Try doing it in a different folder like your desktop.

that is the name of the folder its not actually in the cloud.

**Comment by seanpmaxwell** [comment]
Maybe try using a folder than doesn't have space in the name. I don't know why that would cause issues but I can't think of any other reasons at this point.

**Comment by iampeters** [comment]
> Maybe try using a folder than doesn't have space in the name. I don't know why that would cause issues but I can't think of any other reasons at this point.

ok lemme try that

**Comment by iampeters** [comment]
I think I have found what is really happening.

**What I did**
I created a new project, and ran `npm run build`. the build files were generated in `/dist` folder and when I ran `npm start`, the app worked.

**What I found out**
when I added a `.ts` file in a new folder to `src`, and ran `npm run build` again, the new `ts` file was not compiled. Also, the default files that were compiled initially wasn't compiled on the second run after adding my files.

its really stressing me out. I can share you the link to the repo if you wish to take a look

**Comment by iampeters** [comment]
I have been able to fix my issue.
it turns out that some of the project files were not in the  `src` directory so it couldn't transpile correctly. Also, `tsc` transpiler won't work at all if there are type errors. Thanks a lot for your help @seanpmaxwell

**Comment by seanpmaxwell** [comment]
Oh yeah. If you look at tsconfig it points to src/. You need to modify this file if you want typescript files in other places.
