### ISSUE TITLE
windows error: 'ENV_FILE' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by rasane** [seanpmaxwell/express-generator-typescript#3]
Hi, I just created a new app using command `npx express-generator-typescript api`. I really like the setup, thanks for creating it. 
I also had an issue running it in on windows, as follows.

[nodemon] starting `ENV_FILE=development ts-node -r ./env -r tsconfig-paths/register src/Start.ts`
'ENV_FILE' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...

Just thought i will let you know of the issue and the steps I took to resolve it in my sample project:

1. install `npm install --save-dev cross-env`
2. search for 3 entries for `ENV_FILE=` and replaced with `cross-env ENV_FILE=`, thats it.. verbatim like that..

happy to do a PR if you are okay with the choices..

also, I am able to use this project without the above changes in my Windows Subsystem for Linux (WSL) bash shell.. so, it is optional mostly, just in case..

**Comment by seanpmaxwell** [comment]
Hey awesome, thanks for the free work. I was debating in my head how to make it work for Windows and Linux. Didn't know about cross env. Yeah go ahead and do the pull request. I'll close the issue when done.

**Comment by seanpmaxwell** [comment]
Hey so I implemented your changes since it was a quick fix. Once again, thanks for the help. Version 1.3.0 now uses cross-env.

**Comment by rasane** [comment]
great thanks.. well done for the quick turnaround :-)
