### ISSUE TITLE
Missing tslib and jsonfile as runtime dependencies

### ISSUE THREAD

**Issue by headhunter45** [seanpmaxwell/express-generator-typescript#36]
I'm building an app and packaging it in a docker container. In that container I'm only installing npm prod deps not any packages from devDependencies.  I'm getting errors about the missing modules when I try to run npm start. Here's a minimal repro to simulate the environment.  The second npm install doesn't install tslib and jsonfile.

```
npx express-generator-typescript my-app
cd my-app
echo "{}" > src/public/test.json
npm install
npm run build
# This works
npm start
rm -rf node_modules
npm install --only=prod
# This doesn't work
npm start
```

The jsonfile is needed at runtime because I'm serving static json files.
Adding `"tslib": "^2.0.0"` to dependencies and moving the jsonfile line from devDependencies to dependencies in package.json fixes both of these issues.

**Comment by seanpmaxwell** [comment]
Thanks for pointing this out. I implemented the fix in version 1.6.6
