### ISSUE TITLE
Add VSCode launch.json to README.md

### ISSUE THREAD

**Issue by OfirD1** [seanpmaxwell/express-generator-typescript#40]
I'd like to suggest to add your VSCode `launch.json` config mentioned here #20 to README.md - with a little modification:  

When debugging using that `launch.json`, VSCode issues an error:

    `Could not read source map for file:///path/to/your/express-gen-ts/node_modules/typescript/lib/typescript.js: ENOENT: no such file or directory, open 'path\to\your\express-gen-ts\node_modules\typescript\lib\typescript.js.map'`.

This was resolved in [VSCode issue #102042](https://github.com/microsoft/vscode/issues/102042), and thus we get the following `launch.json`:

      {
            "type": "pwa-node",
            "request": "launch",
            "name": "Debug Dev Env",
            "runtimeArgs": [
                "-r",
                "ts-node/register",
                "-r",
                "tsconfig-paths/register",
            ],
            "args": [
                "${workspaceFolder:express-gen-ts}/src/index.ts"
            ],
            "resolveSourceMapLocations": [
                "${workspaceFolder}/**",
                "!**/node_modules/**"
            ],
       }

**Comment by seanpmaxwell** [comment]
done, thx for your help
