### ISSUE TITLE
'ts-node' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by nathanhannig** [seanpmaxwell/express-generator-typescript#43]
I am on Windows 10.
NPM v7.5.1
Node v15.8.0

```
$ npm run start:dev

> express-gen-ts@0.0.0 start:dev
> nodemon

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: ts,html
[nodemon] starting `ts-node -r tsconfig-paths/register ./src`
'ts-node' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...
```

I change the package.json file nodemonConfig to specify the path.

```
"nodemonConfig": {
    "watch": [
        "src"
    ],
    "ext": "ts, html",
    "ignore": [
        "src/public"
    ],
    "exec": "./node_modules/.bin/ts-node -r tsconfig-paths/register ./src"
},
```

It works.

```
$ npm run start:dev

> express-gen-ts@0.0.0 start:dev
> nodemon

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: ts,html
[nodemon] starting `./node_modules/.bin/ts-node -r tsconfig-paths/register ./src`
```

**Comment by nathanhannig** [comment]
I am not sure if this issue is environmental or not. I am just learning Typescript and wanted to use your npm package to quickly bootstrap a project to begin learning; so apologies if I am missing anything is setting up TS properly.

**Comment by joao-vitor-sr** [comment]
hello, ok to use ts-node it is recommended to use globally 
if you don't want to install globally I recommend you use the _npx_,
here is an example 
`npx ts-node src/main.ts`
and another thing I am not American I am Brazilian then if have some error in my text please alert me

**Comment by joao-vitor-sr** [comment]
Hey Hello,

**Comment by joao-vitor-sr** [comment]
Hello,
have you tried to install the ts-node as a global dependency?

**Comment by seanpmaxwell** [comment]
On windows/linux I do npm i -g ts-node and it works

**Comment by nathanhannig** [comment]
Yes, I am sure it works with installing it globally, but normally installing globals isn't the best practice. It would be best to reference the local install instead?

**Comment by seanpmaxwell** [comment]
Okay I'll update it, maybe this weekend.

**Comment by seanpmaxwell** [comment]
done
