### ISSUE TITLE
Generating project with specified CSS and template engine?

### ISSUE THREAD

**Issue by TheChilliPL** [seanpmaxwell/express-generator-typescript#47]
Is there any way to generate a project with a CSS engine (e.g. SCSS) and template engine (e.g. Pug)?
Can't find if any are preinstalled or if there's a way to install any of them

**Comment by seanpmaxwell** [comment]
No there are no view engines configured because SPA's like React/Angular are so widely used now.

**Comment by TheChilliPL** [comment]
Is it possible to install one manually?

**Comment by seanpmaxwell** [comment]
Of course. After generating a new project with express-generator-typescript, simply go to the Server.ts file, and follow the express documenation on setting up view engines https://expressjs.com/en/guide/using-template-engines.html
