### ISSUE TITLE
Tests are not running in a new created repo

### ISSUE THREAD

**Issue by aserrano1971** [seanpmaxwell/express-generator-typescript#57]
Hi there!

Note: this behavior is happening with the last Mac Monterey release and NodeJS 12 and 16.

In a new repo just recently created the tests are not running
To reproduce this issue just create a new repo with 'express-generator-typescript myrepo' for instance and try to run the tests with 'npm run test'

The error I am receiving is this:

![image](https://user-images.githubusercontent.com/62747173/148022285-77047360-5801-4495-a4cc-8f6d6dea84d0.png)

If I try to fix the type error changing null with undefined and restart:

![image](https://user-images.githubusercontent.com/62747173/148022375-7cee8822-e7c9-4251-b6dc-161ce610cb99.png)

This is what I am receiving:

![image](https://user-images.githubusercontent.com/62747173/148022453-7b73b2f4-08d0-4f90-8773-78c3ec50d073.png)

If I also try to remove the deprecated function:

![image](https://user-images.githubusercontent.com/62747173/148022519-4bae2f6e-51fc-4c88-ba38-0c4d13a217c3.png)

This is what happens:

![image](https://user-images.githubusercontent.com/62747173/148022587-249a68da-d380-465b-a727-efdf75359745.png)

**Comment by seanpmaxwell** [comment]
fixed
