### ISSUE TITLE
Jasmine extension failing with "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by jobwat** [seanpmaxwell/express-generator-typescript#59]
The extension [Jasmine Test Explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-jasmine-test-adapter) is failing on a fresh new generated project:

Step to reproduce:
```
npx express-generator-typescript test
```

`Jasmine Tests` output:
```
(node:75786) UnhandledPromiseRejectionWarning: /private/tmp/test/spec/tests/users.spec.ts:1
import supertest from 'supertest';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Loader.requireShim [as require_] (/Users/yourmum/.vscode/extensions/hbenl.vscode-jasmine-test-adapter-1.7.1/node_modules/jasmine/lib/loader.js:35:3)
    at /Users/yourmum/.vscode/extensions/hbenl.vscode-jasmine-test-adapter-1.7.1/node_modules/jasmine/lib/loader.js:28:12
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:75786) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:75786) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I found a few hints online about the same error but nothing's solving it for me... 

```
$ node --version
v14.17.6
```

**Comment by seanpmaxwell** [comment]
not happening for me, are you using `npm run test`

**Comment by jobwat** [comment]
`npm run test` works

The issue is surfacing when the [Jasmine Test Explorer extension](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-jasmine-test-adapter) is running something (no idea what)

You can see the extension output on the `OUTPUT` tab, selecting `Jasmine Tests`
![image](https://user-images.githubusercontent.com/90534/152896424-0a7d5363-87fc-46ef-b214-b69f91be80a8.png)

**Comment by seanpmaxwell** [comment]
hmmm my guess is vscode is not recognizing typescript

**Comment by jobwat** [comment]
Thanks @seanpmaxwell, you pushed me in the right direction.

I've solved my issue and reported it on the extension repo - https://github.com/hbenl/vscode-jasmine-test-adapter/issues/51

**Comment by jobwat** [comment]
Sorry I don't have anything else than above link. We moved away from typescript since that.

**Comment by jmatonrdx** [comment]
Thank you for a great template.

You need to add some configuration to enable it to work with typescript:

1. File -> Preferences -> Extensions (ctrl+shift+x)

2. Find "Jasmine Test Explorer" in the list of installed extensions, click gear to get to settings.  
  You could also try going to File -> Preferences -> Settings and pasting in:
  @ext:hbenl.vscode-jasmine-test-adapter

3. Click any of the "Edit in settings.json" links (they all go to the same file) and add:
    "jasmineExplorer.nodeArgv": [
        "--require",
        "ts-node/register",
        "--require",
        "tsconfig-paths/register"
    ],
    "jasmineExplorer.env": {
        "TS_NODE_COMPILER_OPTIONS": "{\"module\":\"commonjs\"}"
    },
