### ISSUE TITLE
npm run build doesn't work - Windows

### ISSUE THREAD

**Issue by grmacdonald** [seanpmaxwell/express-generator-typescript#60]
Hi.  When I run 'npm run build' I get the following error:

> typescript_test@0.0.0 build
> ./node_modules/.bin/ts-node build.ts

'.' is not recognized as an internal or external command, operable program or batch file.

I am running this from a Windows machine at the project route.

The odd part is that this worked from my MacBook.
![Build Error](https://user-images.githubusercontent.com/12519213/153928311-2acc848d-9126-4ed0-8563-9c8763a42fe2.png)

Edit: O/S is Windows 11

Thanks.

**Comment by deid84** [comment]
Same for me... after trying other commands I saw that also "npm run start" gave me some errors

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\davide.ferrero\Documents\nodejs\provvisorio\dist'     
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename (C:\Users\davide.ferrero\Documents\nodejs\provvisorio\node_modules\module-alias\index.js:49:29)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) 
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by deid84** [comment]
ok I temporary solved the problem using the abolute path. If you go in package.json you'll find the script that runs the build command (line n. 5 i think).

You'll find that it's a relative path... for now I put the absolute path "C:/Users/xxx/Documents/node/etc...." 

Actually it works for me but i know that it's only a temporary solution.

**Comment by ArtiomOganesyan** [comment]
I added this to scripts

**Comment by seanpmaxwell** [comment]
could you setup a pull request for this

**Comment by marts2390** [comment]
Same issue on Mac..

**Comment by marts2390** [comment]
> Same for me... after trying other commands I saw that also "npm run start" gave me some errors
> 
> ```
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\davide.ferrero\Documents\nodejs\provvisorio\dist'     
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._resolveFilename (C:\Users\davide.ferrero\Documents\nodejs\provvisorio\node_modules\module-alias\index.js:49:29)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) 
>     at node:internal/main/run_main_module:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> ```

I have the same issue on Mac, build command works and compiles the dist folder but running npm start fails with the same error.

**Comment by thehaseebahmed** [comment]
@seanpmaxwell created a PR, please review.

**Comment by seanpmaxwell** [comment]
confirmed the pull request
