### ISSUE TITLE
npm run start doesnt work, initial creation.

### ISSUE THREAD

**Issue by adrian19hub** [seanpmaxwell/express-generator-typescript#66]
immediately after running npx...
![image](https://user-images.githubusercontent.com/79521379/166699541-e27922e8-6d82-4680-821c-52390f0d3ac0.png)

**Comment by thehaseebahmed** [comment]
@adrian19hub Did you run "npm run build" before running "npm run start"?

**Comment by seanpmaxwell** [comment]
@adrian19hub yeah you have to build before running the production code
