### ISSUE TITLE
npm run start is stuck

### ISSUE THREAD

**Issue by thehaseebahmed** [seanpmaxwell/express-generator-typescript#69]
I have not done anything special. Just generated a new project, added sentry and swagger. Everything runs fine with `npm run start:dev` but for some reason, `npm run start` runs and is stuck there indefinitely. 

<img width="474" alt="image" src="https://user-images.githubusercontent.com/11260154/170884173-30278505-8fd8-4c82-82bc-0d8fc7ff7762.png">

Any idea what I might be doing wrong?

**Comment by thehaseebahmed** [comment]
@seanpmaxwell do you have time to look at this?

**Comment by seanpmaxwell** [comment]
did you build the code first?

**Comment by seanpmaxwell** [comment]
Oh I know what the issue is, this actually isn't an issue. For production the logs are printed to a file instead of the console. That's why it hangs like that. If you want to print the logs back to the console you need to update the production.env file under the pre-start/ folder.
