### ISSUE TITLE
Build exits cleanly even if there are errors

### ISSUE THREAD

**Issue by spinningarrow** [seanpmaxwell/express-generator-typescript#70]
In [build.ts](https://github.com/seanpmaxwell/express-generator-typescript/blob/master/sample-output/express-gen-ts/build.ts#L23) when there is an error, the script simply logs it without exiting with a non-zero exit code.

This causes build systems to continue with the build process even though the code may not compile.

A `process.exit(1)` after the log should fix this.

**Comment by seanpmaxwell** [comment]
hmm, can you create a pull request?

**Comment by seanpmaxwell** [comment]
Done
