### ISSUE TITLE
Failed to create a project

### ISSUE THREAD

**Issue by 4piu** [seanpmaxwell/express-generator-typescript#72]
```
~: express-generator-typescript server
/usr/bin/env: ‘node\r’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

```
~: /usr/bin/env node -v
v18.12.1
```

**Comment by seanpmaxwell** [comment]
I just ran the command and it worked `npx express-generator-typescript server`. That error looks like it's an issue with line endings (https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo). Which version of express-generator-typescript are you using? I recommend to clear the npx cache and use that.

**Comment by 4piu** [comment]
I am using `express-generator-typescript@2.2.8` installed by `yarn global add`

**Comment by 4piu** [comment]
And it's indeed a problem with the line ending, I replace all linebreaks in the file `~/.yarn/bin/express-generator-typescript` from Windows to UNIX and now it runs.

**Comment by seanpmaxwell** [comment]
strange, it worked for me both on MaxOS and Ubuntu

**Comment by seanpmaxwell** [comment]
I'm gonna close this. Please create a pull request if you have a fix that can be merged.
