### ISSUE TITLE
run build doesn't copy database.json file over to /dist

### ISSUE THREAD

**Issue by nelsonsbrian** [seanpmaxwell/express-generator-typescript#75]
At least on linux server, the database.json file is missing in the /dist output folder.

**Comment by nelsonsbrian** [comment]
I update my script to this, but I don't think it's OS agnostic.... and I don't know too much about this sort of thing
`"build": "npx ts-node build.ts && cp src/repos/database.json dist/repos/",`

**Comment by seanpmaxwell** [comment]
this is intentional, the mock database.json is only there for demo purposes. You wouldn't want to use a mock database for production, or even development most of the time. Just maybe for rapidly prototyping some objects.

**Comment by seanpmaxwell** [comment]
gonna close this

**Comment by C-Merrill** [comment]
I came across this as well (on Windows, to clear up the OS-agnosticism question). I figured it was likely an intentional decision, but nearly opened an Issue anyway to check. I think a comment somewhere (MockOrm.ts perhaps), or a note in the README wouldn't hurt.
