### ISSUE TITLE
Update instructions for If you don't want authentication: in `README.md` 

### ISSUE THREAD

**Issue by paul-rinaldi** [seanpmaxwell/express-generator-typescript#78]

**Comment by seanpmaxwell** [comment]
Hmm, what need to be updated?

**Comment by paul-rinaldi** [comment]
There's a lot of new auth files and such it seems that I deleted as I started to strip away the auth from the generated server, and some files in the readme don't exist anymore; I'd like to throw in a PR and we'll see if it captures all the right things in a few days after I solve some problems in a diff project. :+1:

**Comment by seanpmaxwell** [comment]
Sounds good.

**Comment by seanpmaxwell** [comment]
hey I'm closing this cause I re-added the `--with-auth` option back to the project, see version 2.4.0.
