### ISSUE TITLE
Best way to add new responses?

### ISSUE THREAD

**Issue by APTGithubAcct** [seanpmaxwell/express-generator-typescript#80]
This project is really detailed, thank you for this.

Where do you recommend we add our own responses to incoming requests so that the project structure stays clean and readable? Server.ts? Or should we make a new file in some sub-folder?

**Comment by seanpmaxwell** [comment]
You should create your own route/services/ and repo files. Name them by what database record they're meant to handle. Like if you have an API for a user to make posts. You should have a PostRoutes.ts, PostsService.ts, and PostRepoo.ts layers.
