### ISSUE TITLE
Thoughts on using this repo in a production environment?

### ISSUE THREAD

**Issue by APTGithubAcct** [seanpmaxwell/express-generator-typescript#81]
I need to set up a web server to be able to handle a few different things, but for now all it needs to do is allow end users to run stored procedures on a remote SQL Server instance. I think this repo is a good starting point for this since it seems to give me a lot of pre-built options. However, I'm curious about its performance and any feedback from other people using this repo. How does this repo fare when running in a production environment with ~1000 users on a variety of devices?

**Comment by seanpmaxwell** [comment]
As good as any other NodeJS/ExpressJS server. Keep in mind you need to built it first `npm run build` and not run the typescript code directly.

**Comment by APTGithubAcct** [comment]
> As good as any other NodeJS/ExpressJS server. Keep in mind you need to built it first `npm run build` and not run the typescript code directly.

In my dev env I'm doing `npm run dev`. When I deploy this to the server where this project will live forever, I just need to do `npm run build` and that's it? Or are there other steps needed in the production env?

**Comment by APTGithubAcct** [comment]
What database do you recommend to store the web server logins?

**Comment by seanpmaxwell** [comment]
What I do is have a lastLogin column for each user. But if you want a record for all logins you need a logging database like elasticsearch, splunk, kafka etc

**Comment by APTGithubAcct** [comment]
Not for last login, I mean for storing credentials in general. I'm going to have about 70 users using this web server, so I'll need to store their credentials somewhere. I noticed that for this github repo I can add a user name & email, but I can't add their password. I'm assuming that might be to encourage people to use a proper database with this, so I was wondering what you would recommend in that regard.

**Comment by seanpmaxwell** [comment]
Dude that's a json file just for show, you need an actual production database. I use postgresql and I store the encrypted password in a separate table called userAuths.

**Comment by APTGithubAcct** [comment]
Ah ok. Sorry for the rookie questions, I'm new to ExpressJS/web server stuff!

**Comment by seanpmaxwell** [comment]
No worries, all the best with your web server
